name = "Damask"
uuid = "7ccfa7fd-a424-414a-8759-eb68cf5c9821"
authors = ["Lisa Vieg <lisa.vieg@alumni.fh-aachen.de>",
           "Martin Diehl <julia@martin-diehl.net>"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Metadata = "4fb893c1-3164-4f58-823a-cb4c64eabb4f"
NaturalSort = "c020b1a1-e9b0-503a-9c33-f039bfc54a85"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
HDF5 = "0.16.0"
Metadata = "0.3.0"
NaturalSort = "1.0.0"
WriteVTK = "1.16.0"
julia = "1.8"
